### ISSUE TITLE
Order Schema

### ISSUE THREAD

**Issue by hannahwood** [hannahwood/stackstore#3]

**Comment by seanbert4** [comment]
Heya, I was mistaken when I suggested that the order status field be a boolean for "completed." In the workshop > requirements > unauthenticated users > checkout, the very last bullet point on the page states that users should "[r]eceive notification emails upon order shipping, then order delivery." So I suspect that orders have to have a status of either "received", "shipped", or "delivered" rather than true/false. 

I don't think orders will have a status of "incomplete," because the way I read workshop > requirements > unauthenticated users > manage their cart, it looks like the cart is being stored exclusively on the front end. An order is only stored in the DB when the user successfully checks out. At least, that's how I read these instructions. This is nice because it means the Order schema never has to flip between live prices and archived prices; it will only ever store the snapshot of the prices as they were when the order was created. 

Let me know your interpretations of the requirements differ! 

I'll put this comment in Hannah's Google Sheets document as well.
